FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build-env
WORKDIR /src

COPY . .

RUN dotnet restore StackOverStadyApi.csproj

RUN dotnet publish StackOverStadyApi.csproj -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build-env /app/publish .

EXPOSE 7295

ENTRYPOINT ["dotnet", "StackOverStadyApi.dll"]